version: "3.8"
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  data: {}