global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  - targets:
    - host.docker.internal:9100

- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets: 
    - host.docker.internal:8080