services:
  postgres:
    container_name: postgres
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  data: {}

networks:
  postgres:
    name: postgres